create table app_access_method (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        tag varchar(255),
        primary key (id)
);

create table app_access_method_deploy_parameters (
  app_access_method_id bigint not null,
  deploy_parameters varchar(255),
  deploy_parameters_key varchar(255) not null,
  primary key (app_access_method_id, deploy_parameters_key)
);

create table app_deployment_spec_access_methods (
  app_deployment_spec_id bigint not null,
  access_methods_id bigint not null unique
);

alter table app_deployment_spec_access_methods add constraint FKd79mobwmaocm1d7bk83hdkow1 foreign key (access_methods_id) references app_access_method;
