create table service_access_method (
        id bigint generated by default as identity,
        name varchar(255),
        type varchar(255),
        url varchar(255),
        protocol varchar(255),
        primary key (id)
);

create table service_access_method_deploy_parameters (
    service_access_method_id bigint not null,
    deploy_parameters varchar(255),
    deploy_parameters_key integer not null,
    primary key (service_access_method_id, deploy_parameters_key)
);

drop table kubernetes_nm_service_info_access_methods;

create table kubernetes_nm_service_info_access_methods (
  kubernetes_nm_service_info_id bigint not null,
  access_methods_id bigint not null unique
);

alter table kubernetes_nm_service_info_access_methods add constraint FKd79mobwmaocm1d7bk39lfuetw foreign key (access_methods_id) references service_access_method;