create table app_storage_volume (
  id bigint generated by default as identity,
  main boolean not null,
  default_storage_space integer not null,
  primary key (id)
);

create table app_storage_volume_deploy_parameters (
  app_storage_volume_id bigint not null,
  deploy_parameters varchar(255),
  deploy_parameters_key varchar(255) not null,
  primary key (app_storage_volume_id, deploy_parameters_key)
);

create table app_deployment_spec_storage_volumes (
  app_deployment_spec_id bigint not null,
  storage_volumes_id bigint not null unique
);

alter table app_deployment_spec_storage_volumes add constraint FKd79mobwmaocm1d7bk88dnat4e foreign key (storage_volumes_id) references app_storage_volume;
