create table service_storage_volume (
  id bigint generated by default as identity,
  main boolean not null,
  size integer not null,
  primary key (id)
);

create table service_storage_volume_deploy_parameters (
    service_storage_volume_id bigint not null,
    deploy_parameters varchar(255),
    deploy_parameters_key integer not null,
    primary key (service_storage_volume_id, deploy_parameters_key)
);

create table kubernetes_nm_service_info_storage_volumes (
  kubernetes_nm_service_info_id bigint not null,
  storage_volumes_id bigint not null unique
);

alter table kubernetes_nm_service_info_storage_volumes add constraint FKd79mobwmaocm1d7bk3likdhbw foreign key (storage_volumes_id) references service_storage_volume;