create sequence hibernate_sequence start 1;

create table revinfo (
  rev integer generated by default as identity,
  revtstmp bigint,
  primary key (rev));

create table user_role_aud (
  domain_id bigint not null,
  role varchar(255) not null,
  user_id bigint not null,
  rev integer not null,
  revtype smallint,
  primary key (domain_id, role, user_id, rev));

create table users_aud (
  id bigint not null,
  rev integer not null,
  revtype smallint,
  email varchar(255),
  enabled boolean,
  firstname varchar(255),
  lastname varchar(255),
  password varchar(255),
  privacy_policy_accepted boolean,
  saml_token varchar(255),
  terms_of_use_accepted boolean,
  username varchar(255),
  primary key (id, rev));


alter table user_role_aud add constraint FK2ax4xks5sy1yh2a2gxdndkcmc foreign key (rev) references revinfo;
alter table users_aud add constraint FKc4vk4tui2la36415jpgm9leoq foreign key (rev) references revinfo;