create table app_description (
  id bigint generated by default as identity,
  brief_description varchar(255) not null,
  full_description text not null,
  language varchar(255) not null,
  primary key (id)
);

create table application_descriptions (
  application_application_id bigint not null,
  descriptions_id bigint not null
);

alter table application drop column brief_description;
alter table application drop column full_description;

alter table application_descriptions add constraint FK11gertncji6seiy4kmvrd2qgf foreign key (descriptions_id) references app_description;
alter table application_descriptions add constraint FK6axxgbdn9ftremvi2nftmuj8y foreign key (application_application_id) references application;
alter table application_descriptions add constraint UK_7pk8srat2d405srdmkcxiwuiy unique (descriptions_id);
