create table application_access_credentials (
  id bigint generated by default as identity,
  username varchar(255) not null,
  password varchar(255) not null,
  primary key (id)
);

alter table nm_service_info add column access_credentials_id bigint;
alter table nm_service_info add constraint FKfyoxqpt5rd8ubfu76a6wwuhy2 foreign key (access_credentials_id) references application_access_credentials;