create table language_mail_content (
       id bigint generated by default as identity,
        language varchar(255) not null,
        subject varchar(255) not null,
        primary key (id)
);

create table language_mail_content_template (
       language_mail_content_id bigint not null,
        template varchar(10485760),
        template_key varchar(255) not null,
        primary key (language_mail_content_id, template_key)
);

create table mail_template (
       id bigint generated by default as identity,
        mail_type integer not null unique,
        primary key (id)
);

create table mail_template_global_information (
      mail_template_id bigint not null,
        global_information varchar(10485760),
        global_information_key varchar(255) not null,
        primary key (mail_template_id, global_information_key)
);

create table mail_template_templates (
     mail_template_id bigint not null,
     templates_id bigint not null
);

alter table app_deployment drop column domain_id;
alter table app_deployment drop column app_instance_id;
alter table app_deployment drop column accessURL;
alter table app_deployment drop column app_instance_name;

alter table app_deployment rename column logged_in_users_name to owner;

alter table language_mail_content_template add constraint FK9lplfbkvn1p6i4ggmaeoyw5bs foreign key (language_mail_content_id) references language_mail_content;
alter table mail_template_templates add constraint FKt5w8klf00id4niddnb9cqw11h foreign key (templates_id) references language_mail_content;
alter table mail_template_templates add constraint FK85vhhf0wihqruuexdjfor1clu foreign key (mail_template_id) references mail_template;