create table language_mail_content (
       id bigint generated by default as identity,
        language varchar(255) not null,
        subject varchar(255) not null,
        template text not null,
        primary key (id)
);

create table mail_template (
       id bigint generated by default as identity,
        mail_type integer not null unique,
        primary key (id)
);

create table mail_template_templates (
     mail_template_id bigint not null,
     templates_id bigint not null
);

alter table app_deployment rename column logged_in_users_name to owner;

alter table mail_template_templates add constraint FKt5w8klf00id4niddnb9cqw11h foreign key (templates_id) references language_mail_content;

alter table mail_template_templates add constraint FK85vhhf0wihqruuexdjfor1clu foreign key (mail_template_id) references mail_template;