create table customer_network(
    id bigint generated by default as identity,
    customer_ip bytea not null,
    mask_length integer not null,
    primary key (id)
);

create table domain_dcn_details_customer_networks (
    domain_dcn_details_id bigint not null,
    customer_networks_id bigint not null
);

alter table domain_dcn_details_customer_networks drop constraint if exists UK_fr3bd3a2audcgroxxdxs6ak6x;
alter table domain_dcn_details_customer_networks add constraint UK_fr3bd3a2audcgroxxdxs6ak6x unique (customer_networks_id);
alter table domain_dcn_details_customer_networks add constraint FKafiq9otakppelaj72i9r8dj74 foreign key (customer_networks_id) references customer_network;
alter table domain_dcn_details_customer_networks add constraint FKjixv8nup6j8eo803u66tl209o foreign key (domain_dcn_details_id) references domain_dcn_details;