-- drop table internationalization if exists;

create table internationalization_simple (id bigint generated by default as identity, enabled boolean not null, language varchar(255) not null, primary key (id));
create table internationalization_simple_language_nodes (
    internationalization_simple_id bigint not null,
    content varchar(1024),
    node_key varchar(255)
);

alter table internationalization_simple add constraint UK_4vac9n7iv51f1o3u39n4nmgfe unique (language);
alter table internationalization_simple_language_nodes add constraint FKhkdvumx2has2syatom23tkkas foreign key (internationalization_simple_id) references internationalization_simple;

insert into internationalization_simple(id, enabled, language)
select id, enabled, language from internationalization;

insert into internationalization_simple_language_nodes(internationalization_simple_id, node_key, content)
with recursive parse_internationalization AS (
    select i.id,
           j.key,
           j.value
    from internationalization i, json_each(i.content::json) j

    UNION ALL

    select p.id,
           concat(p.key, '.', j.key),
           j.value
    from parse_internationalization p, json_each(p.value) j where json_typeof(p.value) != 'string'
) SELECT id, key, TRIM(BOTH '\"' FROM value::text)
    from parse_internationalization where json_typeof(value) = 'string';