# ---------------------- #
# Database configuration #
# ---------------------- #
spring.datasource.url=jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DBNAME}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.connection.autocommit=false
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:/db/migration/common,classpath:/db/migration/postgres
spring.flyway.out-of-order=true

spring.jpa.properties.hibernate.id.db_structure_naming_strategy=legacy
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

oidc.allowedLinkingUsersByEmail=${OIDC_USER_LINKING:true}

spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

upload.dir=/nmaas/files/upload

# nmaas Platform is running within the Kubernetes cluster
nmaas.kubernetes.incluster=true