spring.datasource.url=jdbc:h2:~/nmaas
spring.datasource.username=nmaas
spring.datasource.password=nmaas
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.database=h2
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.connection.autocommit=false
spring.jpa.show-sql=true
spring.h2.console.enabled=true

spring.flyway.enabled=false
spring.flyway.locations=classpath:/db/migration/common
spring.flyway.out-of-order=true

spring.jpa.properties.hibernate.id.db_structure_naming_strategy=legacy
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# ------------------ #
# OIDC configuration #
# ------------------ #
spring.security.oauth2.client.registration.my-oidc.client-id=nmaas-oidc
spring.security.oauth2.client.registration.my-oidc.client-secret=YRM5yBPz3qHAyBr2zpYMhWHbDbQrn6Jl
spring.security.oauth2.client.registration.my-oidc.scope=openid, profile, email
spring.security.oauth2.client.registration.my-oidc.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.my-oidc.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.my-oidc.provider=keycloak
spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:8080/realms/geant/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8080/realms/geant/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.user-info-uri=http://localhost:8080/realms/geant/protocol/openid-connect/userinfo

spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate

upload.dir=./src/test/shell/tmp/