spring.datasource.jdbc-url=jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DBNAME:nmaas}
spring.datasource.username=${POSTGRESQL_USERNAME:nmaas}
spring.datasource.password=${POSTGRESQL_PASSWORD:nmaas}

spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.connection.autocommit=false
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:/db/migration/common,classpath:/db/migration/postgres
spring.flyway.out-of-order=true

spring.jpa.properties.hibernate.id.db_structure_naming_strategy=legacy
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# ------------------ #
# OIDC configuration #
# ------------------ #
spring.security.oauth2.client.registration.my-oidc.client-id=${OIDC_CLIENT_ID:nmaas-oidc}
spring.security.oauth2.client.registration.my-oidc.client-secret=${OIDC_CLIENT_SECRET:YRM5yBPz3qHAyBr2zpYMhWHbDbQrn6Jl}
spring.security.oauth2.client.registration.my-oidc.scope= openid, profile, email
spring.security.oauth2.client.registration.my-oidc.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.my-oidc.redirect-uri={baseUrl}/api/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.my-oidc.issuer-uri=${OIDC_ISSUER_URI:http://localhost:8080/realms/geant}

spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

upload.dir=/nmaas/files/upload