# Active profile
spring.profiles.active=${ENVIRONMENT:local}

# General settings
server.port=${PLATFORM_PORT:9000}
portal.address=${PORTAL_HOST:http://localhost:4200}
admin.password=${ADMIN_PASSWORD:admin}
admin.email=${ADMIN_EMAIL:admin@nmaas.eu}

# REST API documentation
springdoc.api-docs.enabled=${PLATFORM_API_DOCS_ENABLED:false}
springdoc.api-docs.path=/api-docs/spec
springdoc.swagger-ui.enabled=${PLATFORM_API_DOCS_ENABLED:false}
springdoc.swagger-ui.path=/api-docs/ui.html

# Email
spring.mail.username=${SMTP_LOGIN:default}
spring.mail.password=${SMTP_PASSWORD:default}
spring.mail.host=${SMTP_HOST:smtp.nmaas.eu}
spring.mail.port=${SMTP_PORT:587}
spring.mail.properties.mail.smtp.auth=${USE_LOGIN_PASSWORD:true}
spring.mail.properties.mail.smtp.starttls.enable=${USE_STARTTLS:true}
spring.mail.properties.mail.smtp.starttls.required=${USE_STARTTLS:true}
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
# disabled strict check if email configuration is valid
management.health.mail.enabled=false

# Notifications
notifications.from-address=${SMTP_FROM:no-reply@nmaas.eu}

# HTTP filter options
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Actuator and Metrics
nmaas.metrics.enabled=${METRICS_ENABLED:true}
management.endpoints.web.exposure.include=health,prometheus
management.info.git.mode=full

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
spring.devtools.add-properties=false

# -------------------------------------------------------- #
# nmaas application deployment and configuration processes #
# -------------------------------------------------------- #
nmaas.service.deployment.check.interval=${DEPLOYMENT_CHECK_INTERVAL:10}
nmaas.service.deployment.max.duration=${DEPLOYMENT_CHECK_TIMEOUT:120}
nmaas.service.upgrade.cron=${APP_UPGRADE_CRON:0 */5 * * * ?}
nmaas.service.upgrade-summary.cron=${APP_UPGRADE_SUMMARY_CRON:0 0 * * * ?}
nmaas.service.bulk-deployment.cron= 0 */1 * * * ?
nmaas.service.health-check.cron= 0 */5 * * * ?

# interval for which to collect information about last upgrades (in hours)
nmaas.service.upgrade-summary.interval=${APP_UPGRADE_SUMMARY_INTERVAL:24}
nmaas.service.deployment.parallel.limit=2

nmaas.portal.domains.codename.pattern=[a-z0-9-]{2,16}
nmaas.portal.domains.codename.length=16
nmaas.portal.modals.appinstall.pattern=[a-zA-Z0-9-]{3,10}
nmaas.portal.domains.namespace.pattern=[a-z0-9-]{0,64}

nmaas.platform.webhooks.baseurl=${PLATFORM_BASEURL:http://localhost:9000}/api/gitlab/webhooks

# flag indicating if namespace should be created upon domain creation
nmaas.domains.create.namespace=${NAMESPACE_CREATION_ENABLED:false}
nmaas.platform.multi-instance=${MULTI_INSTANCE_DEPLOYMENT:false}

# ------------------------------ #
# Quartz scheduler configuration #
# ------------------------------ #
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always

# ----- #
# Other #
# ----- #
jwt.tokenValidFor=3600000
jwt.refreshTokenValidFor=13600000
jwt.issuer=nmaas
jwt.signingKey=${JWT_SIGNING_KEY:testKey3VhSpqJw9CIw3uHMNNEdo2v3Sqa6MiRFBuJOm7c5vhahIcIj1AWdPUoa1DiWbC0CMBCTqQq1bHYvaJPQUFhF0OwZ41dZtobHH9dRYesuZ8KtWmnohbW6IDupJpns2xku9Dv9BxapDbZVKJKkreKnDACdYsqLKRC0rlwX6iUw2wZWe1Lq9krX1bMFGvy4LQ00kZ0xE9VI49TKOcoM77tVUB7ZTQ1KqSy2ULtszh6wJ15s1PAu6BjKD8ctIEXK1IOh}
jwt.resetSigningKey=${JWT_RESET_KEY:testResetKeyqULvzYiEfsH3fvMVg07ki6MIxULiU279vrNvUYgUNBFVFgNp9Ij74KfCRrQogDosfoT3whUObXOozfnDeyYrB4fMoJNrCeIyDOahEetVNrEj8eQGbaPmPca2e1VrJ3vipSN3mnKeK8aGOe6XLVzLL2a499NgxBQLtuyl4wMGcmEx0TegaL8JsRKw6dH6mQyc8dAAYp9DsxLn9KrEooJsyH6XCeZpQcjlVhwetYlq6iEP2To7OuCigbAWgbwMxhlF}
jwt.resetTokenValidFor=1800000
jwt.resetTokenRegistrationValid=86400000
captcha.secret=${CAPTCHA_SECRET:6LeJgbQUAAAAAIGNksMVgPqiGbdPrYKjXAeeFa5e}
# current pagination issue fix -> set default page size to 1000
# this is still a temporary fix
spring.data.web.pageable.default-page-size=1000

# ------------------ #
# Helm configuration #
# ------------------ #
helm.update.async.enabled=${HELM_UPDATE_ASYNC_ENABLED:true}
helm.update.async.cron=${HELM_UPDATE_ASYNC_CRON:0 0 * * * ?}
helm.repositoryName=${HELM_REPOSITORY:nmaas-test}
helm.enableTls=${HELM_ENABLETLS:false}
# possible values for the Helm version are v2 and v3 (if none is provided v3 is used by default)
helm.version=${HELM_VERSION:v3}

# -------------------- #
# GitLab configuration #
# -------------------- #
gitlab.apiUrl=${GITLAB_API_URL:http://nmaas-gitlab-unicorn:8080}
gitlab.token=${GITLAB_TOKEN:test_gitlab_token}

# ------------------------ #
# Kubernetes configuration #
# ------------------------ #
kubernetes.ingress.controllerConfigOption=USE_EXISTING
kubernetes.ingress.supportedIngressClass=${K8S_INGRESS_CONTROLLER_INGRESS_CLASS:nginx}
kubernetes.ingress.publicIngressClass=${K8S_INGRESS_CONTROLLER_PUBLIC_INGRESS_CLASS:public}
kubernetes.ingress.controllerChartName=nginx
kubernetes.ingress.controllerChartArchive=nginx-ingress.tgz
kubernetes.ingress.resourceConfigOption=DEPLOY_FROM_CHART
kubernetes.ingress.externalServiceDomain=${K8S_INGRESS_CONTROLLER_EXTERNAL_SERVICE_DOMAIN:nmaas.test.net}
kubernetes.ingress.publicServiceDomain=${K8S_INGRESS_CONTROLLER_PUBLIC_SERVICE_DOMAIN:public.nmaas.test.net}
kubernetes.ingress.tlsSupported=${K8S_INGRESS_CONTROLLER_TLS_SUPPORTED:true}
kubernetes.ingress.ingressPerDomain=${K8S_INGRESS_CONTROLLER_PER_DOMAIN:true}
kubernetes.ingress.certificateConfigOption=${K8S_INGRESS_CERTIFICATE_CONFIG_OPTION:USE_LETSENCRYPT}
kubernetes.ingress.issuerOrWildcardName=${K8S_INGRESS_CERTIFICATE_ISSUER_OR_WILDCARD_NAME:nmaas-issuer}
kubernetes.deployment.namespaceConfigOption=${K8S_DEPLOYMENT_NAMESPACE_CONFIG_OPTION:USE_DOMAIN_NAMESPACE}
kubernetes.deployment.defaultNamespace=${K8S_DEPLOYMENT_DEFAULT_NAMESPACE:default}
kubernetes.deployment.forceDedicatedWorkers=false
kubernetes.deployment.smtpServerHostname=${SMTP_HOST:nmaas-postfix}
kubernetes.deployment.smtpServerPort=${SMTP_PORT:587}
kubernetes.deployment.smtpServerUsername=${SMTP_LOGIN:}
kubernetes.deployment.smtpServerPassword=${SMTP_PASSWORD:}
kubernetes.deployment.smtpFromDefaultDomain=${SMTP_FROM_DEFAULT_DOMAIN:}
kubernetes.deployment.defaultStorageClass=${K8S_DEPLOYMENT_DEFAULT_STORAGE_CLASS:storageClass}

# -------------------- #
# Portal configuration #
# -------------------- #
portal.config.maintenance=${PORTAL_MAINTENANCE_FLAG:false}
portal.config.ssoLoginAllowed=${PORTAL_SSO_ALLOWED_FLAG:false}
portal.config.defaultLanguage=${PORTAL_DEFAULT_LANG:en}
portal.config.testInstance=${PORTAL_TEST_INSTANCE_FLAG:false}
portal.config.sendAppInstanceFailureEmails=${PORTAL_SEND_FAILURE_NOTIF_FLAG:false}
portal.config.showDomainRegistrationSelector=${PORTAL_DOMAIN_REGISTRATION_SELECTOR:true}
# string - list of emails with ':' as a separator, e.g., admin1@nmaas.eu;admin2@nmaas.eu
portal.config.appInstanceFailureEmailList=${ADMIN_EMAIL:admin@nmaas.eu}

security.encryption.secret-key=${SECURITY_PBKDF2_SECRET:nmaasplatformgn5}
security.encryption.algorithm=${SECURITY_PBKDF2_ALGORITHM:AES/GCM/NoPadding}

spring.security.oauth2.client.provider.my-oidc.issuer-uri=http://localhost:8081/realms/geant