# ---------------------- #
# Database configuration #
# ---------------------- #
spring.datasource.url=jdbc:h2:~/nmaas
spring.datasource.username=nmaas
spring.datasource.password=nmaas
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.database=h2
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.connection.autocommit=false
spring.jpa.show-sql=true
spring.h2.console.enabled=true

spring.flyway.enabled=false
spring.flyway.locations=classpath:/db/migration/common
spring.flyway.out-of-order=true

spring.jpa.properties.hibernate.id.db_structure_naming_strategy=legacy
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate

upload.dir=./src/test/shell/tmp/

# nmaas Platform is not running within the Kubernetes cluster
nmaas.kubernetes.incluster=false
nmaas.kubernetes.apiserver.url=https://10.1.1.11:6443

spring.security.oauth2.client.provider.my-oidc.issuer-uri=http://localhost:8081/realms/geant