spring.security.oauth2.client.registration.my-oidc.client-id=${OIDC_CLIENT_ID:nmaas-oidc}
spring.security.oauth2.client.registration.my-oidc.client-secret=${OIDC_CLIENT_SECRET:YRM5yBPz3qHAyBr2zpYMhWHbDbQrn6Jl}
spring.security.oauth2.client.registration.my-oidc.scope=openid,profile,email
spring.security.oauth2.client.registration.my-oidc.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.my-oidc.redirect-uri={baseUrl}/api/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.my-oidc.issuer-uri=${OIDC_ISSUER_URI:http://localhost:8080/realms/geant}