package net.geant.nmaas.dcn.deployment.entities;

public enum DcnDeploymentState {

    INIT,
    REQUESTED,
    REQUEST_VERIFIED,
    REQUEST_VERIFICATION_FAILED,
    DEPLOYMENT_INITIATED,
    WAITING_FOR_OPERATOR_CONFIRMATION,
    DEPLOYED,
    DEPLOYMENT_FAILED,
    VERIFICATION_INITIATED,
    VERIFIED,
    VERIFICATION_FAILED,
    REMOVED,
    REMOVAL_INITIATED,
    REMOVAL_FAILED,
    UNKNOWN,
    ERROR

}
