CREATE TABLE variable (
    id bigint PRIMARY KEY generated by default as identity,
    name varchar(100) not null,
    value text not null,
    type varchar(50) not null,
    last_modified bigint not null,
    domain_id bigint
);

alter table variable
   add constraint domain_fk_variable
   foreign key (domain_id)
   references domain;

alter table variable
   add constraint variable_unique_name_per_scope
   unique (domain_id, name);
