CREATE TABLE bundle
(
    id       bigint PRIMARY KEY generated by default as identity,
    codename VARCHAR(255) NOT NULL unique,
    name     VARCHAR(255) NOT NULL
);

CREATE TABLE bundle_description
(
    id                bigint PRIMARY KEY generated by default as identity,
    bundle_id         bigint       NOT NULL,
    language          VARCHAR(255) NOT NULL,
    brief_description VARCHAR(255) NOT NULL,
    full_description  TEXT         NOT NULL,
    CONSTRAINT fk_bundle_description_bundle
        FOREIGN KEY (bundle_id) REFERENCES bundle (id) ON DELETE CASCADE,
    CONSTRAINT uq_bundle_description_bundle_language
        UNIQUE (bundle_id, language)
);

CREATE TABLE bundle_app
(
    bundle_id bigint NOT NULL,
    app_id    bigint NOT NULL,
    CONSTRAINT pk_bundle_app PRIMARY KEY (bundle_id, app_id),
    CONSTRAINT fk_bundle_app_bundle
        FOREIGN KEY (bundle_id) REFERENCES bundle (id) ON DELETE CASCADE,
    CONSTRAINT fk_bundle_app_app
        FOREIGN KEY (app_id) REFERENCES application_base (id) ON DELETE CASCADE
);

CREATE INDEX idx_bundle_app_app_id ON bundle_app (app_id);