CREATE OR REPLACE FUNCTION deployment_state_from_ordinal(state_ordinal integer)
RETURNS varchar(255)
LANGUAGE sql
IMMUTABLE
AS $$
SELECT CASE state_ordinal
           WHEN 0 THEN 'REQUESTED'
           WHEN 1 THEN 'REQUEST_VALIDATED'
           WHEN 2 THEN 'REQUEST_VALIDATION_FAILED'
           WHEN 3 THEN 'DEPLOYMENT_ENVIRONMENT_PREPARATION_IN_PROGRESS'
           WHEN 4 THEN 'DEPLOYMENT_ENVIRONMENT_PREPARED'
           WHEN 5 THEN 'DEPLOYMENT_ENVIRONMENT_PREPARATION_FAILED'
           WHEN 6 THEN 'MANAGEMENT_VPN_CONFIGURED'
           WHEN 7 THEN 'APPLICATION_CONFIGURATION_IN_PROGRESS'
           WHEN 8 THEN 'APPLICATION_CONFIGURED'
           WHEN 9 THEN 'APPLICATION_CONFIGURATION_FAILED'
           WHEN 10 THEN 'APPLICATION_DEPLOYMENT_IN_PROGRESS'
           WHEN 11 THEN 'APPLICATION_DEPLOYED'
           WHEN 12 THEN 'APPLICATION_DEPLOYMENT_VERIFICATION_IN_PROGRESS'
           WHEN 13 THEN 'APPLICATION_DEPLOYMENT_FAILED'
           WHEN 14 THEN 'APPLICATION_DEPLOYMENT_VERIFIED'
           WHEN 15 THEN 'APPLICATION_DEPLOYMENT_VERIFICATION_FAILED'
           WHEN 16 THEN 'APPLICATION_RESTART_IN_PROGRESS'
           WHEN 17 THEN 'APPLICATION_RESTARTED'
           WHEN 18 THEN 'APPLICATION_RESTART_FAILED'
           WHEN 19 THEN 'APPLICATION_PAUSE_IN_PROGRESS'
           WHEN 20 THEN 'APPLICATION_PAUSED'
           WHEN 21 THEN 'APPLICATION_PAUSE_FAILED'
           WHEN 22 THEN 'APPLICATION_RESUME_IN_PROGRESS'
           WHEN 23 THEN 'APPLICATION_RESUMED'
           WHEN 24 THEN 'APPLICATION_RESUME_FAILED'
           WHEN 25 THEN 'APPLICATION_UPGRADE_IN_PROGRESS'
           WHEN 26 THEN 'APPLICATION_UPGRADED'
           WHEN 27 THEN 'APPLICATION_UPGRADE_FAILED'
           WHEN 28 THEN 'APPLICATION_REMOVAL_IN_PROGRESS'
           WHEN 29 THEN 'APPLICATION_REMOVED'
           WHEN 30 THEN 'APPLICATION_REMOVAL_FAILED'
           WHEN 31 THEN 'APPLICATION_CONFIGURATION_REMOVAL_IN_PROGRESS'
           WHEN 32 THEN 'APPLICATION_CONFIGURATION_REMOVED'
           WHEN 33 THEN 'APPLICATION_CONFIGURATION_REMOVAL_FAILED'
           WHEN 34 THEN 'FAILED_APPLICATION_REMOVED'
           WHEN 35 THEN 'APPLICATION_CONFIGURATION_UPDATE_IN_PROGRESS'
           WHEN 36 THEN 'APPLICATION_CONFIGURATION_UPDATED'
           WHEN 37 THEN 'APPLICATION_CONFIGURATION_UPDATE_FAILED'
           WHEN 38 THEN 'INTERNAL_ERROR'
           ELSE NULL
           END
           $$;

ALTER TABLE app_deployment_history
ALTER COLUMN current_state TYPE varchar(255)
    USING deployment_state_from_ordinal(current_state);

ALTER TABLE app_deployment_history
ALTER COLUMN previous_state TYPE varchar(255)
    USING deployment_state_from_ordinal(previous_state);

DROP FUNCTION deployment_state_from_ordinal(integer);