alter table domain drop column dcn_configured;
alter table domain drop column external_service_domain;
alter table domain drop column kubernetes_namespace;
alter table domain drop column kubernetes_storage_class;

create table domain_dcn_details (
    id bigint generated by default as identity,
    dcn_configured boolean,
    dcn_deployment_type varchar(255),
    domain_codename varchar(255) not null,
    primary key (id));

create table domain_tech_details (
    id bigint generated by default as identity,
    domain_codename varchar(255) not null,
    external_service_domain varchar(255),
    kubernetes_namespace varchar(255),
    kubernetes_storage_class varchar(255),
    primary key (id));


alter table domain add column domain_dcn_details_id bigint;
alter table domain add column domain_tech_details_id bigint;
alter table dcn_info add column dcn_deployment_type varchar(255) not null default 'NONE';

alter table domain_dcn_details add constraint UK_q9hq3ukiktil6e84v2bx9n4bc unique (domain_codename);
alter table domain_tech_details add constraint UK_cc6bvj7uo2g5bugv62avdllms unique (domain_codename);
alter table domain_tech_details add constraint UK_cfxgv24r2uuqfo3bafgvdeo9x unique (external_service_domain);
alter table domain add constraint FKomc8uculthnhowkqic6fgb5d3 foreign key (domain_dcn_details_id) references domain_dcn_details;
alter table domain add constraint FKpck49hcl459mb91id9lpgk5uu foreign key (domain_tech_details_id) references domain_tech_details;