alter table app_configuration_spec add terms_acceptance_required boolean not null default false;
alter table app_deployment add terms_acceptance_required boolean not null default false;

create table app_terms_acceptance (
    id bigint generated by default as identity,
    app_name varchar(255) not null,
    username varchar(255) not null,
    terms_acceptance_statement varchar(32) not null ,
    terms_content varchar (500) not null ,
    acceptance_date  timestamp not null,
    primary key(id)
)