create table helm_chart_repository_entity (
                                              id bigint generated by default as identity,
                                              name varchar(14) unique not null,
                                              url varchar(255) unique not null,
                                              primary key (id)
);

insert into helm_chart_repository_entity (name, url) VALUES ('nmaas', 'https://artifactory.software.geant.org/artifactory/nmaas-helm');

alter table kubernetes_template add column helm_chart_repository_id bigint not null default 1;

alter table kubernetes_template
    add constraint FK_HELM_CHART_REPOSITORY
        foreign key (helm_chart_repository_id)
            references helm_chart_repository_entity;