 create table domain_annotations (
       id bigint generated by default as identity,
        key_string varchar(255),
        value_string varchar(255),
        primary key (id)
    );

  alter table domain_annotations
       add constraint UKtcdv5y24mhirqep0f4mlu7ph1 unique (key_string);