create table domain_group (
   id bigint generated by default as identity,
   codename varchar(255) not null,
   name varchar(255) not null,
   primary key (id)
);

alter table domain_group add constraint UK_348chvxdag9lc3ff2u245c6yw unique (codename);
alter table domain_group add constraint UK_joq9w707nkgm57ptb00xan6l1 unique (name);

create table domains_groups (
   domain_id bigint not null,
   group_id bigint not null
);

alter table domains_groups add constraint FKqh8ow3hodjcm6ocbhgy8hjswc foreign key (group_id) references domain_group;
alter table domains_groups add constraint FKm5itt66la68krtm2llico08ov foreign key (domain_id) references domain;
