create table access_tokens (
       id bigint generated by default as identity,
        name varchar(255),
        token_value varchar(255),
        user_id bigint,
        valid boolean not null,
        primary key (id)
 );