drop table access_tokens ;

create table user_api_tokens (
       id bigint generated by default as identity,
        deleted boolean not null,
        name varchar(255),
        token_value varchar(255),
        user_id bigint,
        valid boolean not null,
        primary key (id)
 );

 alter table if exists user_api_tokens
        add constraint FK96apkd4dubtiefdvwpk6kuew7
        foreign key (user_id)
        references users;