create table cluster_manager (
        creation_date timestamp(6) with time zone not null,
        deployment_id bigint unique,
        id bigint generated by default as identity,
        ingress_id bigint unique,
        modification_date timestamp(6) with time zone not null,
        cluster_config_file varchar(255) not null,
        codename varchar(255) not null,
        description varchar(255) not null,
        name varchar(255) not null,
        path_config_file varchar(255) not null,
        primary key (id)
    );

create table clusters_domains (
            cluster_id bigint not null,
            domain_id bigint not null
);

create table kcluster_deployment (
        force_dedicated_workers boolean,
        namespace_config_option tinyint check (namespace_config_option between 0 and 2),
        smtp_server_port integer,
        id bigint generated by default as identity,
        default_namespace varchar(255),
        default_storage_class varchar(255),
        smtp_from_default_domain varchar(255),
        smtp_server_hostname varchar(255),
        smtp_server_password varchar(255),
        smtp_server_username varchar(255),
        primary key (id)
    );

create table kcluster_ingress (
        certificate_config_option tinyint check (certificate_config_option between 0 and 1),
        controller_config_option tinyint check (controller_config_option between 0 and 2),
        ingress_per_domain boolean,
        resource_config_option tinyint check (resource_config_option between 0 and 1),
        tls_supported boolean,
        id bigint generated by default as identity,
        controller_chart_archive varchar(255),
        controller_chart_name varchar(255),
        external_service_domain varchar(255),
        issuer_or_wildcard_name varchar(255),
        public_ingress_class varchar(255),
        public_service_domain varchar(255),
        supported_ingress_class varchar(255),
        primary key (id)
    );

alter table if exists cluster_manager
       add constraint FKkw3lst58qvj1fmots9sjrl31o
       foreign key (deployment_id)
       references kcluster_deployment;

 alter table if exists cluster_manager
       add constraint FKa4x6r57mr7vk69fn8xlqchonb
       foreign key (ingress_id)
       references kcluster_ingress;

alter table if exists clusters_domains
       add constraint FKndxrsyl952klcberdqvvd5484
       foreign key (domain_id)
       references domain;

alter table if exists clusters_domains
       add constraint FKch3yhxvbwsutlu14hcw2vah3k
       foreign key (cluster_id)
       references cluster_manager;