CREATE TABLE webhooks (
    id bigint PRIMARY KEY generated by default as identity,
    name VARCHAR(255) NOT NULL  unique,
    target_url VARCHAR(255) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    token_value VARCHAR(2056),
    authorization_header VARCHAR(50)
);