CREATE TABLE resources_limit (
    id bigint PRIMARY KEY generated by default as identity,
    memory integer not null,
    cpu integer not null,
    instances_no integer not null,
    containers_no integer not null,
    limit_type varchar(50) not null,
    domain_group_id bigint,
    domain_id bigint
);

alter table resources_limit
   add constraint domain_group_fk_resources_limit
   foreign key (domain_group_id)
   references domain_group;

alter table resources_limit
   add constraint domain_fk_resources_limit
   foreign key (domain_id)
   references domain;