CREATE TABLE webhook_history (
    id bigint PRIMARY KEY generated by default as identity,
    event_type VARCHAR(50) NOT NULL,
    domain_codename VARCHAR(255),
    url VARCHAR(255) NOT NULL,
    request_body CLOB NOT NULL,
    response_status VARCHAR(255),
    response_body CLOB,
    execution_timestamp timestamp NOT NULL
);