package net.geant.nmaas.orchestration;

/**
 * Application lifecycle states as presented to the {@link AppLifecycleManager} client.
 *
 * @author Lukasz Lopatowski <llopat@man.poznan.pl>
 */
public enum AppLifecycleState {

    REQUESTED,
    REQUEST_VALIDATION_IN_PROGRESS,
    REQUEST_VALIDATED,
    REQUEST_VALIDATION_FAILED,
    DEPLOYMENT_ENVIRONMENT_PREPARATION_IN_PROGRESS,
    DEPLOYMENT_ENVIRONMENT_PREPARED,
    DEPLOYMENT_ENVIRONMENT_PREPARATION_FAILED,
    MANAGEMENT_VPN_CONFIGURATION_IN_PROGRESS,
    MANAGEMENT_VPN_CONFIGURED,
    MANAGEMENT_VPN_CONFIGURATION_FAILED,
    APPLICATION_CONFIGURATION_IN_PROGRESS,
    APPLICATION_CONFIGURED,
    APPLICATION_CONFIGURATION_FAILED,
    APPLICATION_DEPLOYMENT_IN_PROGRESS,
    APPLICATION_DEPLOYED,
    APPLICATION_DEPLOYMENT_FAILED,
    APPLICATION_DEPLOYMENT_VERIFICATION_IN_PROGRESS,
    APPLICATION_DEPLOYMENT_VERIFIED,
    APPLICATION_DEPLOYMENT_VERIFICATION_FAILED,
    APPLICATION_REMOVAL_IN_PROGRESS,
    APPLICATION_REMOVED,
    APPLICATION_REMOVAL_FAILED,
    UNKNOWN,
    INTERNAL_ERROR,
    GENERIC_ERROR;

}
