// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/nmaas-janitor.proto

package net.geant.nmaas.externalservices.inventory.janitor;

public final class JanitorManager {
  private JanitorManager() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**compile group: 'com.google.protobuf', name: 'protobuf-java', version: '3.6.0'
   * Protobuf enum {@code v1.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FAILED = 0;</code>
     */
    FAILED(0),
    /**
     * <code>OK = 1;</code>
     */
    OK(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FAILED = 0;</code>
     */
    public static final int FAILED_VALUE = 0;
    /**
     * <code>OK = 1;</code>
     */
    public static final int OK_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    public static Status forNumber(int value) {
      switch (value) {
        case 0: return FAILED;
        case 1: return OK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:v1.Status)
  }

  public interface InstanceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v1.Instance)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string namespace = 1;</code>
     */
    java.lang.String getNamespace();
    /**
     * <code>string namespace = 1;</code>
     */
    com.google.protobuf.ByteString
        getNamespaceBytes();

    /**
     * <code>string uid = 2;</code>
     */
    java.lang.String getUid();
    /**
     * <code>string uid = 2;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>string domain = 3;</code>
     */
    java.lang.String getDomain();
    /**
     * <code>string domain = 3;</code>
     */
    com.google.protobuf.ByteString
        getDomainBytes();
  }
  /**
   * Protobuf type {@code v1.Instance}
   */
  public  static final class Instance extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v1.Instance)
      InstanceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Instance.newBuilder() to construct.
    private Instance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Instance() {
      namespace_ = "";
      uid_ = "";
      domain_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Instance(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              namespace_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              domain_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_Instance_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_Instance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.class, net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.Builder.class);
    }

    public static final int NAMESPACE_FIELD_NUMBER = 1;
    private volatile java.lang.Object namespace_;
    /**
     * <code>string namespace = 1;</code>
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      }
    }
    /**
     * <code>string namespace = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UID_FIELD_NUMBER = 2;
    private volatile java.lang.Object uid_;
    /**
     * <code>string uid = 2;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>string uid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOMAIN_FIELD_NUMBER = 3;
    private volatile java.lang.Object domain_;
    /**
     * <code>string domain = 3;</code>
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      }
    }
    /**
     * <code>string domain = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, namespace_);
      }
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uid_);
      }
      if (!getDomainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, domain_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, namespace_);
      }
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uid_);
      }
      if (!getDomainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, domain_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance)) {
        return super.equals(obj);
      }
      net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance other = (net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance) obj;

      boolean result = true;
      result = result && getNamespace()
          .equals(other.getNamespace());
      result = result && getUid()
          .equals(other.getUid());
      result = result && getDomain()
          .equals(other.getDomain());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getNamespace().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getDomain().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v1.Instance}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v1.Instance)
        net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.InstanceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_Instance_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_Instance_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.class, net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.Builder.class);
      }

      // Construct using net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        namespace_ = "";

        uid_ = "";

        domain_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_Instance_descriptor;
      }

      @java.lang.Override
      public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance getDefaultInstanceForType() {
        return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.getDefaultInstance();
      }

      @java.lang.Override
      public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance build() {
        net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance buildPartial() {
        net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance result = new net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance(this);
        result.namespace_ = namespace_;
        result.uid_ = uid_;
        result.domain_ = domain_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance) {
          return mergeFrom((net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance other) {
        if (other == net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.getDefaultInstance()) return this;
        if (!other.getNamespace().isEmpty()) {
          namespace_ = other.namespace_;
          onChanged();
        }
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (!other.getDomain().isEmpty()) {
          domain_ = other.domain_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object namespace_ = "";
      /**
       * <code>string namespace = 1;</code>
       */
      public java.lang.String getNamespace() {
        java.lang.Object ref = namespace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          namespace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string namespace = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNamespaceBytes() {
        java.lang.Object ref = namespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          namespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string namespace = 1;</code>
       */
      public Builder setNamespace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        namespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 1;</code>
       */
      public Builder clearNamespace() {
        
        namespace_ = getDefaultInstance().getNamespace();
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 1;</code>
       */
      public Builder setNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        namespace_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <code>string uid = 2;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uid = 2;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 2;</code>
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 2;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object domain_ = "";
      /**
       * <code>string domain = 3;</code>
       */
      public java.lang.String getDomain() {
        java.lang.Object ref = domain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          domain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string domain = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDomainBytes() {
        java.lang.Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string domain = 3;</code>
       */
      public Builder setDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        domain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string domain = 3;</code>
       */
      public Builder clearDomain() {
        
        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }
      /**
       * <code>string domain = 3;</code>
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        domain_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:v1.Instance)
    }

    // @@protoc_insertion_point(class_scope:v1.Instance)
    private static final net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance();
    }

    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Instance>
        PARSER = new com.google.protobuf.AbstractParser<Instance>() {
      @java.lang.Override
      public Instance parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Instance(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Instance> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Instance> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfigUpdateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v1.ConfigUpdateRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string api = 1;</code>
     */
    java.lang.String getApi();
    /**
     * <code>string api = 1;</code>
     */
    com.google.protobuf.ByteString
        getApiBytes();

    /**
     * <code>.v1.Instance deployment = 2;</code>
     */
    boolean hasDeployment();
    /**
     * <code>.v1.Instance deployment = 2;</code>
     */
    net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance getDeployment();
    /**
     * <code>.v1.Instance deployment = 2;</code>
     */
    net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.InstanceOrBuilder getDeploymentOrBuilder();
  }
  /**
   * Protobuf type {@code v1.ConfigUpdateRequest}
   */
  public  static final class ConfigUpdateRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v1.ConfigUpdateRequest)
      ConfigUpdateRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigUpdateRequest.newBuilder() to construct.
    private ConfigUpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigUpdateRequest() {
      api_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigUpdateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              api_ = s;
              break;
            }
            case 18: {
              net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.Builder subBuilder = null;
              if (deployment_ != null) {
                subBuilder = deployment_.toBuilder();
              }
              deployment_ = input.readMessage(net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(deployment_);
                deployment_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_ConfigUpdateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_ConfigUpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest.class, net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest.Builder.class);
    }

    public static final int API_FIELD_NUMBER = 1;
    private volatile java.lang.Object api_;
    /**
     * <code>string api = 1;</code>
     */
    public java.lang.String getApi() {
      java.lang.Object ref = api_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        api_ = s;
        return s;
      }
    }
    /**
     * <code>string api = 1;</code>
     */
    public com.google.protobuf.ByteString
        getApiBytes() {
      java.lang.Object ref = api_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        api_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPLOYMENT_FIELD_NUMBER = 2;
    private net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance deployment_;
    /**
     * <code>.v1.Instance deployment = 2;</code>
     */
    public boolean hasDeployment() {
      return deployment_ != null;
    }
    /**
     * <code>.v1.Instance deployment = 2;</code>
     */
    public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance getDeployment() {
      return deployment_ == null ? net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.getDefaultInstance() : deployment_;
    }
    /**
     * <code>.v1.Instance deployment = 2;</code>
     */
    public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.InstanceOrBuilder getDeploymentOrBuilder() {
      return getDeployment();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getApiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, api_);
      }
      if (deployment_ != null) {
        output.writeMessage(2, getDeployment());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getApiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, api_);
      }
      if (deployment_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDeployment());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest)) {
        return super.equals(obj);
      }
      net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest other = (net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest) obj;

      boolean result = true;
      result = result && getApi()
          .equals(other.getApi());
      result = result && (hasDeployment() == other.hasDeployment());
      if (hasDeployment()) {
        result = result && getDeployment()
            .equals(other.getDeployment());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + API_FIELD_NUMBER;
      hash = (53 * hash) + getApi().hashCode();
      if (hasDeployment()) {
        hash = (37 * hash) + DEPLOYMENT_FIELD_NUMBER;
        hash = (53 * hash) + getDeployment().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v1.ConfigUpdateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v1.ConfigUpdateRequest)
        net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_ConfigUpdateRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_ConfigUpdateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest.class, net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest.Builder.class);
      }

      // Construct using net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        api_ = "";

        if (deploymentBuilder_ == null) {
          deployment_ = null;
        } else {
          deployment_ = null;
          deploymentBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_ConfigUpdateRequest_descriptor;
      }

      @java.lang.Override
      public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest getDefaultInstanceForType() {
        return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest.getDefaultInstance();
      }

      @java.lang.Override
      public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest build() {
        net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest buildPartial() {
        net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest result = new net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest(this);
        result.api_ = api_;
        if (deploymentBuilder_ == null) {
          result.deployment_ = deployment_;
        } else {
          result.deployment_ = deploymentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest) {
          return mergeFrom((net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest other) {
        if (other == net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest.getDefaultInstance()) return this;
        if (!other.getApi().isEmpty()) {
          api_ = other.api_;
          onChanged();
        }
        if (other.hasDeployment()) {
          mergeDeployment(other.getDeployment());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object api_ = "";
      /**
       * <code>string api = 1;</code>
       */
      public java.lang.String getApi() {
        java.lang.Object ref = api_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          api_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string api = 1;</code>
       */
      public com.google.protobuf.ByteString
          getApiBytes() {
        java.lang.Object ref = api_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          api_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string api = 1;</code>
       */
      public Builder setApi(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        api_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string api = 1;</code>
       */
      public Builder clearApi() {
        
        api_ = getDefaultInstance().getApi();
        onChanged();
        return this;
      }
      /**
       * <code>string api = 1;</code>
       */
      public Builder setApiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        api_ = value;
        onChanged();
        return this;
      }

      private net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance deployment_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance, net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.Builder, net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.InstanceOrBuilder> deploymentBuilder_;
      /**
       * <code>.v1.Instance deployment = 2;</code>
       */
      public boolean hasDeployment() {
        return deploymentBuilder_ != null || deployment_ != null;
      }
      /**
       * <code>.v1.Instance deployment = 2;</code>
       */
      public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance getDeployment() {
        if (deploymentBuilder_ == null) {
          return deployment_ == null ? net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.getDefaultInstance() : deployment_;
        } else {
          return deploymentBuilder_.getMessage();
        }
      }
      /**
       * <code>.v1.Instance deployment = 2;</code>
       */
      public Builder setDeployment(net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance value) {
        if (deploymentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deployment_ = value;
          onChanged();
        } else {
          deploymentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.v1.Instance deployment = 2;</code>
       */
      public Builder setDeployment(
          net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.Builder builderForValue) {
        if (deploymentBuilder_ == null) {
          deployment_ = builderForValue.build();
          onChanged();
        } else {
          deploymentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.v1.Instance deployment = 2;</code>
       */
      public Builder mergeDeployment(net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance value) {
        if (deploymentBuilder_ == null) {
          if (deployment_ != null) {
            deployment_ =
              net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.newBuilder(deployment_).mergeFrom(value).buildPartial();
          } else {
            deployment_ = value;
          }
          onChanged();
        } else {
          deploymentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.v1.Instance deployment = 2;</code>
       */
      public Builder clearDeployment() {
        if (deploymentBuilder_ == null) {
          deployment_ = null;
          onChanged();
        } else {
          deployment_ = null;
          deploymentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.v1.Instance deployment = 2;</code>
       */
      public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.Builder getDeploymentBuilder() {
        
        onChanged();
        return getDeploymentFieldBuilder().getBuilder();
      }
      /**
       * <code>.v1.Instance deployment = 2;</code>
       */
      public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.InstanceOrBuilder getDeploymentOrBuilder() {
        if (deploymentBuilder_ != null) {
          return deploymentBuilder_.getMessageOrBuilder();
        } else {
          return deployment_ == null ?
              net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.getDefaultInstance() : deployment_;
        }
      }
      /**
       * <code>.v1.Instance deployment = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance, net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.Builder, net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.InstanceOrBuilder> 
          getDeploymentFieldBuilder() {
        if (deploymentBuilder_ == null) {
          deploymentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance, net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Instance.Builder, net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.InstanceOrBuilder>(
                  getDeployment(),
                  getParentForChildren(),
                  isClean());
          deployment_ = null;
        }
        return deploymentBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:v1.ConfigUpdateRequest)
    }

    // @@protoc_insertion_point(class_scope:v1.ConfigUpdateRequest)
    private static final net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest();
    }

    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigUpdateRequest>
        PARSER = new com.google.protobuf.AbstractParser<ConfigUpdateRequest>() {
      @java.lang.Override
      public ConfigUpdateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigUpdateRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigUpdateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigUpdateRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfigUpdateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v1.ConfigUpdateResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string api = 1;</code>
     */
    java.lang.String getApi();
    /**
     * <code>string api = 1;</code>
     */
    com.google.protobuf.ByteString
        getApiBytes();

    /**
     * <code>.v1.Status status = 2;</code>
     */
    int getStatusValue();
    /**
     * <code>.v1.Status status = 2;</code>
     */
    net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Status getStatus();

    /**
     * <code>string message = 3;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code v1.ConfigUpdateResponse}
   */
  public  static final class ConfigUpdateResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v1.ConfigUpdateResponse)
      ConfigUpdateResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigUpdateResponse.newBuilder() to construct.
    private ConfigUpdateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigUpdateResponse() {
      api_ = "";
      status_ = 0;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigUpdateResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              api_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_ConfigUpdateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_ConfigUpdateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse.class, net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse.Builder.class);
    }

    public static final int API_FIELD_NUMBER = 1;
    private volatile java.lang.Object api_;
    /**
     * <code>string api = 1;</code>
     */
    public java.lang.String getApi() {
      java.lang.Object ref = api_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        api_ = s;
        return s;
      }
    }
    /**
     * <code>string api = 1;</code>
     */
    public com.google.protobuf.ByteString
        getApiBytes() {
      java.lang.Object ref = api_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        api_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>.v1.Status status = 2;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.v1.Status status = 2;</code>
     */
    public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Status getStatus() {
      @SuppressWarnings("deprecation")
      net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Status result = net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Status.valueOf(status_);
      return result == null ? net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Status.UNRECOGNIZED : result;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getApiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, api_);
      }
      if (status_ != net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Status.FAILED.getNumber()) {
        output.writeEnum(2, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getApiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, api_);
      }
      if (status_ != net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Status.FAILED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse)) {
        return super.equals(obj);
      }
      net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse other = (net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse) obj;

      boolean result = true;
      result = result && getApi()
          .equals(other.getApi());
      result = result && status_ == other.status_;
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + API_FIELD_NUMBER;
      hash = (53 * hash) + getApi().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v1.ConfigUpdateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v1.ConfigUpdateResponse)
        net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_ConfigUpdateResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_ConfigUpdateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse.class, net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse.Builder.class);
      }

      // Construct using net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        api_ = "";

        status_ = 0;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.internal_static_v1_ConfigUpdateResponse_descriptor;
      }

      @java.lang.Override
      public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse getDefaultInstanceForType() {
        return net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse.getDefaultInstance();
      }

      @java.lang.Override
      public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse build() {
        net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse buildPartial() {
        net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse result = new net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse(this);
        result.api_ = api_;
        result.status_ = status_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse) {
          return mergeFrom((net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse other) {
        if (other == net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse.getDefaultInstance()) return this;
        if (!other.getApi().isEmpty()) {
          api_ = other.api_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object api_ = "";
      /**
       * <code>string api = 1;</code>
       */
      public java.lang.String getApi() {
        java.lang.Object ref = api_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          api_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string api = 1;</code>
       */
      public com.google.protobuf.ByteString
          getApiBytes() {
        java.lang.Object ref = api_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          api_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string api = 1;</code>
       */
      public Builder setApi(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        api_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string api = 1;</code>
       */
      public Builder clearApi() {
        
        api_ = getDefaultInstance().getApi();
        onChanged();
        return this;
      }
      /**
       * <code>string api = 1;</code>
       */
      public Builder setApiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        api_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.v1.Status status = 2;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.v1.Status status = 2;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.v1.Status status = 2;</code>
       */
      public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Status getStatus() {
        @SuppressWarnings("deprecation")
        net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Status result = net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Status.valueOf(status_);
        return result == null ? net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.v1.Status status = 2;</code>
       */
      public Builder setStatus(net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.v1.Status status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 3;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 3;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 3;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 3;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:v1.ConfigUpdateResponse)
    }

    // @@protoc_insertion_point(class_scope:v1.ConfigUpdateResponse)
    private static final net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse();
    }

    public static net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigUpdateResponse>
        PARSER = new com.google.protobuf.AbstractParser<ConfigUpdateResponse>() {
      @java.lang.Override
      public ConfigUpdateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigUpdateResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigUpdateResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigUpdateResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.geant.nmaas.externalservices.inventory.janitor.JanitorManager.ConfigUpdateResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_Instance_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_Instance_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_ConfigUpdateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_ConfigUpdateRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_ConfigUpdateResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_ConfigUpdateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035resources/nmaas-janitor.proto\022\002v1\":\n\010I" +
      "nstance\022\021\n\tnamespace\030\001 \001(\t\022\013\n\003uid\030\002 \001(\t\022" +
      "\016\n\006domain\030\003 \001(\t\"D\n\023ConfigUpdateRequest\022\013" +
      "\n\003api\030\001 \001(\t\022 \n\ndeployment\030\002 \001(\0132\014.v1.Ins" +
      "tance\"P\n\024ConfigUpdateResponse\022\013\n\003api\030\001 \001" +
      "(\t\022\032\n\006status\030\002 \001(\0162\n.v1.Status\022\017\n\007messag" +
      "e\030\003 \001(\t*\034\n\006Status\022\n\n\006FAILED\020\000\022\006\n\002OK\020\0012\211\001" +
      "\n\rConfigService\022;\n\006Create\022\027.v1.ConfigUpd" +
      "ateRequest\032\030.v1.ConfigUpdateResponse\022;\n\006" +
      "Update\022\027.v1.ConfigUpdateRequest\032\030.v1.Con" +
      "figUpdateResponseBD\n2net.geant.nmaas.ext" +
      "ernalservices.inventory.janitorB\016Janitor" +
      "Managerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_v1_Instance_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v1_Instance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_Instance_descriptor,
        new java.lang.String[] { "Namespace", "Uid", "Domain", });
    internal_static_v1_ConfigUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_v1_ConfigUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_ConfigUpdateRequest_descriptor,
        new java.lang.String[] { "Api", "Deployment", });
    internal_static_v1_ConfigUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_v1_ConfigUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_ConfigUpdateResponse_descriptor,
        new java.lang.String[] { "Api", "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
