package net.geant.nmaas.notifications.templates;

public enum MailType {
    REGISTRATION,
    ACCOUNT_ACTIVATED,
    ACCOUNT_BLOCKED,
    APP_DEPLOYED,
    EXTERNAL_SERVICE_HEALTH_CHECK,
    PASSWORD_RESET,
    CONTACT_FORM,
    APP_ACTIVE,
    APP_REJECTED,
    APP_NEW,
    APP_DELETED,
    APP_NOT_ACTIVE,
    NEW_SSO_LOGIN,
    BROADCAST,
    APP_DEPLOYMENT_FAILED,
    NEW_DOMAIN_REQUEST,
    ISSUE_REPORT,
    APP_UPGRADE_POSSIBLE,
    APP_UPGRADED,
    APP_UPGRADE_SUMMARY
}
